ALTER TYPE "Tema" ADD VALUE 'HORROR';
ALTER TYPE "Tema" ADD VALUE 'DRAMA';
ALTER TYPE "Tema" ADD VALUE 'TELENOVELA';
ALTER TYPE "Tema" ADD VALUE 'EXPERIMENTAL';
ALTER TYPE "Tema" ADD VALUE 'FANTASIA';
ALTER TYPE "Tema" ADD VALUE 'THRILLER';
